apiVersion: v1
kind: ServiceAccount
metadata:
  name: dis-agent
  namespace: dis-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dis-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes", "events"]
    verbs: ["get", "list", "watch", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dis-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dis-agent-role
subjects:
  - kind: ServiceAccount
    name: dis-agent
    namespace: dis-system
